# Generated by Django 4.0.6 on 2022-10-22 20:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Thumbnail',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/Thumbnail'), upload_to=''),
        ),
    ]
