# Generated by Django 4.0.6 on 2022-10-23 10:39

import Manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0002_manga_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Thumbnail',
            field=models.ImageField(default='default/noimage.png', upload_to=Manga.models.Manga.image_upload_to),
        ),
    ]
