# Generated by Django 4.0.6 on 2022-10-23 12:14

import Manga.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0003_alter_manga_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 15, 14, 35, 504844)),
        ),
        migrations.AlterField(
            model_name='manga',
            name='Thumbnail',
            field=models.ImageField(default='default/noimage.png', max_length=255, upload_to=Manga.models.Manga.image_upload_to),
        ),
    ]
