# Generated by Django 4.0.6 on 2022-10-23 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0004_chapter_pub_date_alter_manga_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='Translator',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 16, 35, 40, 27648)),
        ),
        migrations.DeleteModel(
            name='Translators',
        ),
    ]
